import { Video } from "@remotion/media";
import {
  AbsoluteFill,
  Easing,
  interpolate,
  Sequence,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { BrollOverlay, brollPlan } from "../data/brollPlan";

// Renders B-roll clips as muted, opacity-crossfaded overlays on top of the
// A-roll. CRITICAL: this layer is VISUAL-ONLY. The A-roll's audio (the
// speaker's voice in viral-cut.mp4) keeps playing uninterrupted underneath
// because:
//   1. We never replace or unmount the A-roll <Video> in ViralBody — it
//      stays mounted for the entire body duration.
//   2. Each B-roll <Video> below has `muted` + `volume={0}`, contributing
//      nothing to the audio mix.
// So speech continuity with the on-screen captions is preserved across
// every B-roll cut. Plan is generated by scripts/plan-broll.mjs.
export const BrollOverlayLayer: React.FC = () => {
  const { fps } = useVideoConfig();
  if (brollPlan.length === 0) return null;
  return (
    <AbsoluteFill style={{ pointerEvents: "none" }}>
      {brollPlan.map((b, i) => {
        const from = Math.max(0, Math.round(b.startSec * fps));
        const dur = Math.max(1, Math.round((b.endSec - b.startSec) * fps));
        return (
          <Sequence key={i} from={from} durationInFrames={dur} layout="none">
            <BrollClip overlay={b} />
          </Sequence>
        );
      })}
    </AbsoluteFill>
  );
};

const FADE_SEC = 0.4;

const BrollClip: React.FC<{ overlay: BrollOverlay }> = ({ overlay }) => {
  const frame = useCurrentFrame();
  const { fps, durationInFrames } = useVideoConfig();

  const fadeFrames = Math.max(1, Math.round(FADE_SEC * fps));
  const inT = interpolate(frame, [0, fadeFrames], [0, 1], {
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });
  const outT = interpolate(
    frame,
    [durationInFrames - fadeFrames, durationInFrames],
    [1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );
  const opacity = inT * outT;

  const trimBeforeFrames = Math.max(0, Math.round(overlay.clipStartSec * fps));

  return (
    <AbsoluteFill style={{ opacity, background: "#000" }}>
      {/* Belt + suspenders: `muted` excludes the B-roll's audio track from
          the rendered MP4 entirely, and `volume={0}` ensures any leaked
          stream is silent. Only the speaker's voice (from the A-roll
          beneath this layer) reaches the viewer. */}
      <Video
        src={staticFile(overlay.clipFile)}
        trimBefore={trimBeforeFrames}
        muted
        volume={0}
        style={{ width: "100%", height: "100%", objectFit: "cover" }}
      />
      {/* Subtle warm vignette so the cut between A and B-roll feels coherent
          with the rest of the edit. */}
      <AbsoluteFill
        style={{
          pointerEvents: "none",
          background:
            "radial-gradient(ellipse at center, rgba(0,0,0,0) 60%, rgba(14,10,6,0.55) 100%)",
        }}
      />
    </AbsoluteFill>
  );
};
