import { Video } from "@remotion/media";
import {
  AbsoluteFill,
  Easing,
  interpolate,
  Sequence,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { BrollOverlay, brollPlan } from "../data/brollPlan";

// Renders B-roll clips as muted, opacity-crossfaded overlays on top of the
// A-roll. The A-roll's audio (the speaker's voice) keeps playing underneath.
// Plan is generated by scripts/plan-broll.mjs (Ollama-curated).
export const BrollOverlayLayer: React.FC = () => {
  const { fps } = useVideoConfig();
  if (brollPlan.length === 0) return null;
  return (
    <AbsoluteFill style={{ pointerEvents: "none" }}>
      {brollPlan.map((b, i) => {
        const from = Math.max(0, Math.round(b.startSec * fps));
        const dur = Math.max(1, Math.round((b.endSec - b.startSec) * fps));
        return (
          <Sequence key={i} from={from} durationInFrames={dur} layout="none">
            <BrollClip overlay={b} />
          </Sequence>
        );
      })}
    </AbsoluteFill>
  );
};

const FADE_SEC = 0.4;

const BrollClip: React.FC<{ overlay: BrollOverlay }> = ({ overlay }) => {
  const frame = useCurrentFrame();
  const { fps, durationInFrames } = useVideoConfig();

  const fadeFrames = Math.max(1, Math.round(FADE_SEC * fps));
  const inT = interpolate(frame, [0, fadeFrames], [0, 1], {
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });
  const outT = interpolate(
    frame,
    [durationInFrames - fadeFrames, durationInFrames],
    [1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );
  const opacity = inT * outT;

  const trimBeforeFrames = Math.max(0, Math.round(overlay.clipStartSec * fps));

  return (
    <AbsoluteFill style={{ opacity, background: "#000" }}>
      <Video
        src={staticFile(overlay.clipFile)}
        trimBefore={trimBeforeFrames}
        muted
        style={{ width: "100%", height: "100%", objectFit: "cover" }}
      />
      {/* Subtle warm vignette so the cut between A and B-roll feels coherent
          with the rest of the edit. */}
      <AbsoluteFill
        style={{
          pointerEvents: "none",
          background:
            "radial-gradient(ellipse at center, rgba(0,0,0,0) 60%, rgba(14,10,6,0.55) 100%)",
        }}
      />
    </AbsoluteFill>
  );
};
