#!/usr/bin/env node
// Produce `public/main-polished.mp4`:
//  - Drops every silent segment detected in `src/data/silences.ts`
//    (keeps 80 ms of breathing room on either side of each cut).
//  - Aggressive speech-isolation + artifact suppression pipeline:
//      agate     — gates out background below -45 dB (kills room tone,
//                  mic bumps, AC hum spikes when nobody's talking)
//      afftdn    — FFT-based broadband noise reduction
//      anlmdn    — non-local means denoiser for residual hiss
//      highpass/lowpass — bandpass the vocal range only
//      dynaudnorm — window-based dynamic normalization: keeps voice at a
//                   consistent level across the whole video, no muffled
//                   quiet bits or loud spikes
//      acompressor — tames any transients that slip through dynaudnorm
//      loudnorm  — final -18 LUFS web target
//      alimiter  — brick-wall safety at -1.6 dB
//
// Usage:
//   node scripts/polish-audio.mjs
//
// Requires system ffmpeg (the Remotion-bundled ffmpeg lacks these filters).

import { spawn } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";

const SILENCES_TS = "src/data/silences.ts";
const INPUT = "public/07_AKMSHAMIUL ISLAM.MP4";
const OUTPUT = "public/main-polished.mp4";
const CUTMAP_TS = "src/data/cutmap.ts";
const FILTER_FILE = "scripts/.filter_complex.txt";

const PAD = 0.06; // trim tighter than before to kill more dead air

// ---------- parse silences.ts ----------
const tsText = await readFile(SILENCES_TS, "utf8");
const match = tsText.match(
  /export const silences[^=]*=\s*(\{[\s\S]*?\n\});/,
);
if (!match) {
  throw new Error("Could not extract silences JSON from src/data/silences.ts");
}
const silences = JSON.parse(match[1]);
const totalSec = silences.totalDurationSec;

// ---------- compute kept segments ----------
/** @type {[number, number][]} */
const kept = [];
let cursor = 0;
for (const s of silences.segments) {
  const start = cursor;
  const end = Math.max(cursor, s.startSec + PAD);
  if (end - start > 0.05) kept.push([start, end]);
  cursor = Math.min(totalSec, s.endSec - PAD);
}
if (cursor < totalSec) kept.push([cursor, totalSec]);

// Merge neighbours that overlap after padding.
const merged = [];
for (const [s, e] of kept) {
  const last = merged[merged.length - 1];
  if (last && s <= last[1] + 0.01) last[1] = Math.max(last[1], e);
  else merged.push([s, e]);
}

const trimmedSec = merged.reduce((sum, [s, e]) => sum + (e - s), 0);
console.log(
  `${silences.segments.length} silences | ` +
    `${totalSec.toFixed(2)}s original -> ${trimmedSec.toFixed(2)}s trimmed ` +
    `(cut ${(totalSec - trimmedSec).toFixed(2)}s across ${merged.length} kept segments)`,
);

// ---------- write cutmap.ts ----------
const cutmapSrc = `export type KeptSegment = [startSec: number, endSec: number];

// Auto-generated by scripts/polish-audio.mjs — do not edit.
// Each tuple is a non-silent span kept in public/main-polished.mp4,
// expressed in the coordinates of the ORIGINAL source video.
export const keptSegments: KeptSegment[] = ${JSON.stringify(merged)};

export const originalDurationSec = ${totalSec};
export const trimmedDurationSec = ${trimmedSec};

/**
 * Remap a timestamp from the original video's timeline onto the trimmed
 * (silence-removed) timeline. If the timestamp falls inside a removed
 * range, returns the boundary of the nearest kept segment.
 */
export const remapTime = (originalSec: number): number => {
  let t = 0;
  for (const [s, e] of keptSegments) {
    if (originalSec < s) return t;
    if (originalSec < e) return t + (originalSec - s);
    t += e - s;
  }
  return t;
};
`;
await writeFile(CUTMAP_TS, cutmapSrc);
console.log(`wrote ${CUTMAP_TS}`);

// ---------- build filter_complex ----------
const lines = [];
for (let i = 0; i < merged.length; i++) {
  const [s, e] = merged[i];
  lines.push(`[0:v]trim=start=${s}:end=${e},setpts=PTS-STARTPTS[v${i}]`);
  lines.push(`[0:a]atrim=start=${s}:end=${e},asetpts=PTS-STARTPTS[a${i}]`);
}
let concatIns = "";
for (let i = 0; i < merged.length; i++) concatIns += `[v${i}][a${i}]`;
lines.push(
  `${concatIns}concat=n=${merged.length}:v=1:a=1[vout][aconcat]`,
);

// Speech-clarity chain. Order matters: gate out background BEFORE denoise
// so afftdn's noise profile isn't trained on real speech dips; denoise
// before dynaudnorm so the normalizer isn't amplifying hiss between words.
lines.push(
  "[aconcat]" +
    [
      "agate=threshold=-45dB:ratio=9:attack=3:release=120:knee=6dB",
      "afftdn=nr=30:nt=w:tn=1",
      "anlmdn=s=8:p=0.004:r=0.006",
      "highpass=f=95:poles=2",
      "lowpass=f=11500:poles=2",
      "dynaudnorm=f=150:g=7:p=0.7:m=15:s=12",
      "acompressor=threshold=-20dB:ratio=3:attack=4:release=200:makeup=2",
      "loudnorm=I=-18:TP=-1.6:LRA=5",
      "alimiter=limit=0.83:attack=3:release=80",
    ].join(",") +
    "[aout]",
);

const filterScript = lines.join(";\n");
await writeFile(FILTER_FILE, filterScript);
console.log(`filter_complex written to ${FILTER_FILE} (${lines.length} filters)`);

// ---------- run ffmpeg ----------
const args = [
  "-hide_banner",
  "-nostats",
  "-y",
  "-i",
  INPUT,
  "-filter_complex_script",
  FILTER_FILE,
  "-map",
  "[vout]",
  "-map",
  "[aout]",
  "-c:v",
  "libx264",
  "-preset",
  "medium",
  "-crf",
  "20",
  "-pix_fmt",
  "yuv420p",
  "-r",
  "30",
  "-c:a",
  "aac",
  "-b:a",
  "192k",
  "-ar",
  "48000",
  OUTPUT,
];

console.log(`running ffmpeg -> ${OUTPUT}`);
const child = spawn("ffmpeg", args, { stdio: "inherit" });
const exit = await new Promise((r) => child.on("close", r));
if (exit !== 0) {
  console.error(`ffmpeg failed with exit code ${exit}`);
  process.exit(exit);
}
console.log("done");
