export type BrollOverlay = {
  startSec: number;
  endSec: number;
  clipFile: string;
  clipStartSec: number;
  reason?: string;
};

// Auto-generated by scripts/plan-broll.mjs (single tail overlay).
// One B-roll clip plays once at the end of the viral cut, ending
// 0.50s before the body finishes so it acts as a smooth visual handoff
// into the CTA outro. To regenerate, re-run `npm run plan:broll`
// (or pass -WithBroll to the pipeline).

export const brollPlan: BrollOverlay[] = [
  {
    "startSec": 70.232,
    "endSec": 74.732,
    "clipFile": "broll/Student_arrives_Japan_202604271525.mp4",
    "clipStartSec": 0,
    "reason": "Tail handoff into the CTA — student arriving in Japan visually lands the 'come to Japan with Imas Frontier' message."
  }
];
