export type BrollOverlay = {
  startSec: number;       // viral-cut timeline: when overlay appears
  endSec: number;         // viral-cut timeline: when overlay ends
  clipFile: string;       // path under public/, e.g. "broll/dhaka-classroom.mp4"
  clipStartSec: number;   // offset within the source clip to start playback
  reason?: string;        // why the model picked this overlay (for review)
};

// Auto-generated by scripts/plan-broll.mjs (Ollama-curated B-roll plan).
// Empty array = no B-roll layer rendered. Drop your own clips into
// public/broll/ and re-run `npm run plan:broll` (or pass -WithBroll to the
// pipeline) to populate this file.

export const brollPlan: BrollOverlay[] = [];
