export type TriCaption = {
  startSec: number;
  endSec: number;
  en: string;
  jp: string;
  bn: string;
  position?: "top" | "bottom";
};

// Auto-generated by scripts/build-captions.mjs from public/transcript.json
// (Whisper transcription of main-enhanced.mp4 in ORIGINAL-time seconds),
// remapped to TRIMMED-time seconds via src/data/cutmap.ts.
//
// Third-language fields (jp for bn-source segments, bn for ja-source) come
// from public/translations.json, written by scripts/fill-third-lang.py.
//
// To rebuild:
//   python scripts/transcribe.py public/main-enhanced.mp4
//   python scripts/fill-third-lang.py
//   node scripts/build-captions.mjs

export const captions: TriCaption[] = [
  {
    "startSec": 0,
    "endSec": 1.68,
    "en": "Hi, I am Pooja.",
    "jp": "",
    "bn": "হাই কেছে দেখিসে"
  },
  {
    "startSec": 2.277,
    "endSec": 19.31,
    "en": "Let's start with a self-introduction. Nice to meet you. My name is Samuel. I'm in my early 30s.",
    "jp": "ではサミュールさんよろしくお願いしますまず自己紹介からお願いできますか初めましてサミュールと申します年齢は30代前半です",
    "bn": "চল নিজে নিজে নিজে থেকে শুরু করি। দেখা হয়ে ভালো লাগলো। আমার নাম স্যামুয়েল। আমি ৩০ মিনিটের মধ্যে আছি।"
  },
  {
    "startSec": 19.31,
    "endSec": 24.968,
    "en": "I am learning the production of the Japanese ability test.",
    "jp": "日本語能力試験減算を習得しています",
    "bn": "আমি জাপানি দক্ষতা পরীক্ষার উৎপাদন শেখাচ্ছি।"
  },
  {
    "startSec": 24.968,
    "endSec": 35.964,
    "en": "It's been about two and a half years since I came to Japan. I am currently working as an IT engineer in Japan. Thank you for your cooperation.",
    "jp": "日本に聞いては大体2年半になっています。今は日本でITエンジニアとして働いています。よろしくお願いします。",
    "bn": "প্রায় দেড় বছর হয়ে গেছে আমি জাপানে এসেছি। আমি বর্তমানে জাপানে আইটি ইঞ্জিনিয়ার হিসেবে কাজ করছি। সাহায্যের জন্য ধন্যবাদ."
  },
  {
    "startSec": 38.588,
    "endSec": 42.354,
    "en": "Why did you decide to go to Japan?",
    "jp": "日本に行きたいと思った理由は何ですか",
    "bn": "কেন আপনি জাপানে যাওয়ার সিদ্ধান্ত নিয়েছিলেন?"
  },
  {
    "startSec": 42.354,
    "endSec": 58.126,
    "en": "In my case, there are two main reasons. One is that I am an IT engineer and I was interested in A related work. While living in Bangladesh, in a Japanese company,",
    "jp": "私の場合、主な理由は2つあります。 一つは、ITエンジニアであり、関連業務に興味を持ちました。 バングラデシュに住む中、日本企業、",
    "bn": "আমার কেস্ত্রে প্রধনত কারণ বলা জাই দুতো যেতো আমি এক জন IT ইঞ্জিনিয়ের এবং এই রিলেটেট আসুলে কাজকরের বাপারে আগ্র হয়ছিল"
  },
  {
    "startSec": 58.126,
    "endSec": 73.333,
    "en": "I have been working in this field for almost 45 years. So, I was very proud of it. And there is a great opportunity in Japan for IT engineers. If you want to challenge yourself, if you want to improve yourself, there is a great opportunity.",
    "jp": "ここまで45年で働いています。 とても誇りに思います。 そして、ITエンジニアにとって日本には素晴らしい機会があります。 自分でチャレンジしたい場合は、自分で改善したいなら、素晴らしい機会があります。",
    "bn": "45 কোছেরের কাছা কাছি কাছ করিছি তো এখেত্রে আমার আগ্রো ছিলো এবং জাপানে আইটি ইঞ্জিনিয়ার হিসেবে বেশ ভালো অপর্টিনিটি আ�"
  },
  {
    "startSec": 73.333,
    "endSec": 85.877,
    "en": "This is one reason and the second reason is Japan's lifestyle. Everything here is very clean and organized. Cleanliness is also very important. That's why I came to Japan.",
    "jp": "日本でのライフスタイルを第一に考える理由です。 ここにすべてが非常にきれいで整理されています。 清潔感も非常に重要です。 そういうわけで日本に来たんです。",
    "bn": "তো এটা একটা কারণ এবং দিতি ওটি হচ্ছে জাপনের লাইফ স্টাইল তো এখানে সব কিছু নিয়ন তারণ মাফিক হয় এবং পরিষ্কার পরেছুনো সব ক�"
  },
  {
    "startSec": 86.361,
    "endSec": 91.475,
    "en": "How do you feel before and after coming to Japan?",
    "jp": "日本に来る前の印象と来てからの印象はいかがですか",
    "bn": "জাপানে আসার আগে এবং পরে আপনার কেমন লাগছে?"
  },
  {
    "startSec": 92.173,
    "endSec": 105.823,
    "en": "As I said earlier, I have been working for a Japanese company in Bangladesh for about 5 years.",
    "jp": "先ほど述べたように、バングラデシュで約5年間日本企業で働いています。",
    "bn": "্যামন্তা একটো আগে বলেছিলাম বাংলাদেশে থাকা কেলিন আমি আসলে জাপনিস একটি কমপানির বাংলাদেশি ব্রাংচে প্রাই পাঁছ বছরে কা�"
  },
  {
    "startSec": 105.823,
    "endSec": 118.211,
    "en": "about business culture and Japanese culture. But as much as I was aware of it, the way life was going on in Asia,",
    "jp": "事業文化・日本文化について しかし、そのことを意識していた限り、アジアで生活する方法は、",
    "bn": "business culture এবং জাপানের কাল্চার সম্প্রকে কিছলা ধারণা ছিলো কিন্তু জত্তাই ধারণা থাবুক নেকনে আসলে এসে জিবদিলাত্রা যামন্টা হয় আ"
  },
  {
    "startSec": 118.211,
    "endSec": 125.239,
    "en": "I don't know if I should be worried about the fact that Shatika was pregnant, but what do you think about this mystery?",
    "jp": "シャチカが妊娠していたという事実を心配すべきかどうかはわかりませんが、この謎についてどう思いますか?",
    "bn": "সত্তিকার যে উপলোগ থি সেটা আস্সলে চিন্তা হবনাথে এক টানোর রোগনি হয়ন তো এইদিমিস্টের কি মনে রখাও ছিছো"
  },
  {
    "startSec": 127.036,
    "endSec": 130.471,
    "en": "What did you think was good about living in Japan?",
    "jp": "日本に来てよかったと思った点は何ですか?",
    "bn": "জাপানে বাস করা নিয়ে তুমি কি ভাব?"
  },
  {
    "startSec": 130.471,
    "endSec": 146.467,
    "en": "First of all, what I want to say is that everything here is legal. So, in our country, the fact that in this case, it may be a little selfish, but in Japan, everything is legal. Even if the rules are a little difficult, everything is legal.",
    "jp": "まず第一に、私が望むことは、ここにあるすべてが法的であるということです。 ですから、我が国では、このケースでは少し自滅するかもしれませんが、日本では、すべてが法的です。 ルールが少し難しい場合でも、全てが法的です。",
    "bn": "প্রথমন্তো যেটা বলতে চাই সবকিছ এখনে নিয়ম মাফিক হয় আমাথের দেশে যেজিনিস্টা দেখা যায় যে এখিত্রে হয়তে একটো নিস্বি"
  },
  {
    "startSec": 146.467,
    "endSec": 150.724,
    "en": "I think this is very positive for me.",
    "jp": "私はこれが私にとって非常に肯定的だと思う。",
    "bn": "মেনে এবং সকিক সমাই পালন করা হয়ে এই জনিষ্টা আমার কাছে বিস্ট পাজিটিক মনে হয়েছে"
  },
  {
    "startSec": 150.848,
    "endSec": 163.602,
    "en": "What is the problem in Japan? As an IT engineer, I came to Japan. In the beginning, I would say that even though I used to work in a Japanese company",
    "jp": "では逆に日本で困ったことは何ですか?",
    "bn": "জাপানে সমস্যা কি? একজন আইটি ইঞ্জিনিয়ার হিসেবে, আমি জাপানে এসেছিলাম । শুরুতে আমি বলব যে যদিও আমি কোন জাপানি কোম্পানীর সাথে কাজ করতাম"
  },
  {
    "startSec": 163.602,
    "endSec": 178.079,
    "en": "The working culture in Bangladesh and the working culture in Japan is a bit different. So, it may take some time to think about it and come to a conclusion.",
    "jp": "バングラデシュの労働文化と日本での労働文化は少し異なります。 そこで、それについて考え、結論に来るのに時間がかかることがあります。",
    "bn": "্বান্লেতেশে আসলে কাছকরার কাল্চার এবং জাপানে সলস্রি কাছকরার কাছকরার কাছকরার কাছকরার এটা আমি মনে কিছুতা আলাদা এজন্ন প"
  },
  {
    "startSec": 178.261,
    "endSec": 192.454,
    "en": "What do you want to do in Japan in the future? I have been living in Japan for almost 2 years now. I have a family.",
    "jp": "これから日本にしたいのは? 日本で2年近く暮らしています。 私は家族を持っています。",
    "bn": "Kongo নিহন দে দো স্তে ইকিতাই তো মত্তেমাস কা? এখন যে তু জাপনে প্রায় দুই পছ্ছোর আরেই বছ্ছরের কাছে কাছে আমি আছি তো বর্তম�"
  },
  {
    "startSec": 192.454,
    "endSec": 196.696,
    "en": "the Japanese law and also how",
    "jp": "日本法と日本の法",
    "bn": "্যাপনে নিয়ম কানন মিনে এবং সেই সাথে কি হাবে"
  },
  {
    "startSec": 197.311,
    "endSec": 209.886,
    "en": "I would like to be a part of this society. I want to be a part of this society. I want to be a part of this society.",
    "jp": "この社会の一員になりたいと思っています。 この社会の一員になりたい。 この社会の一員になりたい。",
    "bn": "এই সসাইটিতে একিন বা এই সমাজে কি ভাবে আরো এক জন সদাশ্যি স্যাবে অবধান রাছিতে পারি সেরকোম ভাবে চলতে চাই সেই সাথে অবশোই"
  },
  {
    "startSec": 209.886,
    "endSec": 215.05,
    "en": "to improve the quality of the work.",
    "jp": "仕事の質を改善するために。",
    "bn": "্যে যোক্কোতা কিমে কাজিনে কিই হবে আরো ইপ্রুফ্ক করা যে সেটা চানেজ করতে যে"
  },
  {
    "startSec": 217.635,
    "endSec": 234.177,
    "en": "What do you think about living in Japan for Bangladeshis? First of all, I think most of the Bangladeshis in Japan are Muslims. The first thing they can face is not eating.",
    "jp": "バングラデシュの日本に住むことについてどう思いますか? まず第一に、日本ではバングラデシュのほとんどがイスラム教徒だと思う。 直面できるのは食べることではありません。",
    "bn": "্বাংগুলা দেশুজিন নিতোত্তে নিহন দেনো সেকাত্সা দো ময়মস্কা? প্রথমে যদি একেত্রে বলতে হয় যাপনে আশার কর আমি মনে করি �"
  },
  {
    "startSec": 234.177,
    "endSec": 242.209,
    "en": "In Japan, there is a lot of delicious food but in our case, we can't eat anything other than halal food.",
    "jp": "日本では、美味しい食べ物がたくさんありますが、私たちの場合、ハラールフード以外のものは食べません。",
    "bn": "তো জাপানে অনেক দেখাছে দেশুস্যা একিমো মজাদার খাবার আছে কিন্তু আমাদের কেট্য দেখাছে যে হালাল খাবার ছালা যে হিতে পার�"
  },
  {
    "startSec": 242.209,
    "endSec": 256.323,
    "en": "So, in this case, the first step may be a little challenging. But there are many halal shops in the present and many supermarkets are showing halal food. In that case, we can solve the problem by using various apps or talking to the next person.",
    "jp": "ですから、この場合、最初のステップは少し難しいかもしれません。 しかし、現時点では多くのハラールショップがあり、多くのスーパーマーケットがハラールフードを見せています。 その場合、様々なアプリや、次の人に話して問題を解決することができます。",
    "bn": "তো এই কেত্রে প্রথন প্রথন হাপার একটি চেলেন্জিংগ মনে হোতে পারে কিন্তু বর্তমানে অনেক হালাল দুকান আছে এবং অনেক সুপার"
  },
  {
    "startSec": 256.909,
    "endSec": 263.441,
    "en": "Do you have any advice for those who are studying Japanese in Bangladesh?",
    "jp": "今バングラデシュで日本語を勉強している方々に何かアドバイスはありますか",
    "bn": "যারা জাপানে পড়াশোনা করছেন তাদের জন্য আপনার কি কোন উপদেশ আছে?"
  },
  {
    "startSec": 263.441,
    "endSec": 279.422,
    "en": "In Bangladesh, my personal opinion is that JLPT N4 or JLPT N3 may not be a problem in Japan, but it is a mistake. Here, the main focus is communication.",
    "jp": "バングラデシュでは、私の個人的な意見は、JLPT N4 または JLPT N3 が日本では問題ではないかもしれないということですが、それは間違いです。 ここは、メインフォーカスがコミュニケーションです。",
    "bn": "তো ভাংলাদেশে থাকালিন আমার বেক্তিগতো যে অফিক্ষত আসলে অনেকেম অনেকারা যে JLPT N4 অথবা JLPT N3 থাকলে আসলে হয়েতো জাপনে গিয়ে ত"
  },
  {
    "startSec": 279.422,
    "endSec": 292.654,
    "en": "JLPT certificate and the ability to communicate are two different things. For this, I would like to give a suggestion to everyone. First of all, listen to Japanese and practice it.",
    "jp": "JLPTの証明書と通信能力は2つの異なることです。 そのためには、みんなに提案してほしい。 まず、日本語を聞いて練習しましょう。",
    "bn": "JLPT র সার্টিফিকের থাকা এবং কোমিনিকেশনের এবলিটি তোরি করে দোটালা দেবে পার। এছন্ন আমি বিক্তিক হয়েবে সাইশন দিকো হচ্ছে"
  },
  {
    "startSec": 292.654,
    "endSec": 299.358,
    "en": "Practice it a lot so that when you come to Japan, you don't have any communication issues.",
    "jp": "日本に来ると、コミュニケーションの問題がなくても、たくさん練習しましょう。",
    "bn": "কাথা সুনে সেটা বেশে বেশে প্রাক্টিস করে যানো জাপানে আসার পর কোমিনিকেশন একে তেটামন কোন সমসা না হয়।"
  },
  {
    "startSec": 299.593,
    "endSec": 306.373,
    "en": "Is there anything you would like to say to the Bangladeshi people who want to go to Japan?",
    "jp": "日本へ行きたいと考えているバングラデシュの方々に何か言いたいことはありますか",
    "bn": "বাংলাদেশের যে সমস্ত নাগরিক জাপানে যেতে চায়, তাদের কাছে কি আপনি কিছু বলতে চান?"
  },
  {
    "startSec": 306.606,
    "endSec": 311.45,
    "en": "In this case, I will definitely say those who are coming from abroad.",
    "jp": "この場合、海外から来ている人たちは間違いなく言うでしょう。",
    "bn": "A এক কেত্রে আমি বল্বো অবশোই যেতু বিদেশা আস্ছেন"
  },
  {
    "startSec": 311.45,
    "endSec": 333.642,
    "en": "is very different from the laws of Bangladesh. In this case, I would suggest everyone to follow the laws of Japan, if you are familiar with them or if you have come here through any agency, then follow these laws and maintain this mentality. Because you just have to...",
    "jp": "バングラデシュの法律とは違います。 この場合は、皆さんが日本法に従うよう勧めます。もしあなたがそれらに精通しているか、もしあなたがどんな機関から来ているのか、そしてこれらの法則に従い、この精神性を維持すればいいでしょう。 ・・・",
    "bn": "a দেশের নিয়াম কানন বাংগালাদেশের নিয়াম কানন থেকে অনেকটাই আলাতা এখেরতে আমার অনুরোত থাকবে সবাই অবশ্বই যাপানের নিয়া�"
  },
  {
    "startSec": 333.642,
    "endSec": 334.405,
    "en": "",
    "jp": "",
    "bn": "ানা"
  },
  {
    "startSec": 334.405,
    "endSec": 344.57,
    "en": "You are not representing Bangladesh here. This is necessary so that we can manage it well. Don't worry about this and try to follow it.",
    "jp": "バングラデシュの代表的ではありません。 よく管理できるように必要です。 心配しないでください。",
    "bn": "নিয়া আসছেন না আপনি বাংগাদেশকেও আসল এখনে রিপ্রেজেন্ট করতেছেন এছন্ন এই জনিষ্ট আবশ্যিনিয়ম কানো যানো ভালবে মেনে চ�"
  },
  {
    "startSec": 347.802,
    "endSec": 364.318,
    "en": "My name is Banglai Prashna. Most of the people who came for this interview don't know about our company. They don't know anything about us. So, what are we going to start with?",
    "jp": "私の名前はBanglai Prashnaです。 このインタビューに来たほとんどの人は、当社について知りません。 私たちについて何も知りません。 それでは、どうなるの?",
    "bn": "আমারতের বাংলায় প্রশ্নারকে যারো কাপনে মতামটি আরকি আমাদের কম্পনিয়ারকি যারা আস্কের ইন্ট্রবিয়ের পার্পাজেবং কম্প�"
  },
  {
    "startSec": 364.318,
    "endSec": 371.918,
    "en": "The company's purpose is to open up Bangladesh Hector Languages which is the tagline of Onystop Solution.",
    "jp": "同社の目的は、Onystop Solutionのタグラインであるバングラデシュのヘクター言語を開くことです。",
    "bn": "o নারা কমপানিটা যে পর্পাজনে বাংগলাদেশ এক্টা লেম্যেজে স্কুল শুডু করতে ছে যেটা টেগলাইন হচ্ছু অনিস্টপ সলুশন"
  },
  {
    "startSec": 371.918,
    "endSec": 389.914,
    "en": "So, what do you think about this? Do you think that this is the way to do it? Or if you have any suggestions for us, do you think it is our strength... ...or do you think that our students here have a low level of expectation?",
    "jp": "それでは、どう思いますか? これを行う方法は? あるいは、私たちの提案があれば、それが私たちの強みであると思います...それとも、私たちの学生が期待の低レベルを持っていると思いますか?",
    "bn": "So, সে কেত্রা আপনা মতমত কি আনি কেমার মনাহয়ার কি অন্যান্যার দেছে কি আমাদের অতোবা আমাদের চন্ডাবে যদি কোনো সাজেশন থাক�"
  },
  {
    "startSec": 390.586,
    "endSec": 406.358,
    "en": "As far as I know, I have heard a lot about other agencies. I don't have any personal experience, but I have heard a lot from the students. I believe that the students are the target of most of the agencies.",
    "jp": "知っている限り、他の機関についてよく聞いています。 個人的な経験はありませんが、学生から多く聞いています。 ほとんどの機関のターゲットである学生は信じています。",
    "bn": "A কেত্রে আমি যততকো ভুষ্তে করেছি অন্যান্য এজিদি সম্পরকে যততকো সনেছি আমার বেক্তি গাতো যে তো ভিক্যতা নি কিন্তো যতত�"
  },
  {
    "startSec": 406.358,
    "endSec": 421.172,
    "en": "to earn money. So, what happened after that? Did they follow the rules properly? Even if they got the job properly, this is not possible. Most of the agencies, I am not talking about everyone, some agencies are exceptional, but most of the agencies do not worry about this.",
    "jp": "お金を稼ぐために。 それでは、その後に何が起こったのか? ルールをきちんと守っていましたか? きちんと仕事をしたとしても、これは不可能です。 ほとんどの代理店、私は皆について話していません、一部の代理店は例外的ですが、ほとんどの代理店はこのことを心配しません。",
    "bn": "পার করতে পেরে টাকাই নিকাউন করা তো এরপরে আসার পরে আসলে কি হোলো তারা নিয়মকারণ ঠিকমত্ত মানুলো কিনা ঠিকমত্ত চাক্তে পে�"
  },
  {
    "startSec": 421.172,
    "endSec": 438.004,
    "en": "So, what you are thinking now is that you will prepare in such a way that they can come and work in the working visa. So, with this target, in the same way, you will prepare and train. I am seeing this positively because your target is...",
    "jp": "そこで、今は、就労ビザで働けるような方法で準備を進めるつもりです。 そのため、このターゲットを同じ方法で準備して訓練します。 目標は...",
    "bn": "তো যেতো এখন আপনেরা যেতো চিন্তে আমনা করছেন যে এমন ফাবে প্রস্তুত করবেন যানো এসেই তারা ঵ার্কিংগ ভিসায়তে যানো কাশ ক�"
  },
  {
    "startSec": 455.932,
    "endSec": 459.449,
    "en": "I am going to take a nap.",
    "jp": "私はナップを取るつもりです.",
    "bn": "্যানে নম্তে তুলেখে তোমাই তাকাস শোলিতে হনিকে বাইতে"
  }
];
