export type KeptSegment = [startSec: number, endSec: number];

// Auto-generated by scripts/polish-audio.mjs — do not edit.
// Each tuple is a non-silent span kept in public/main-polished.mp4,
// expressed in the coordinates of the ORIGINAL source video.
export const keptSegments: KeptSegment[] = [[0,501.005]];

export const originalDurationSec = 501.005;
export const trimmedDurationSec = 501.005;

/**
 * Remap a timestamp from the original video's timeline onto the trimmed
 * (silence-removed) timeline. If the timestamp falls inside a removed
 * range, returns the boundary of the nearest kept segment.
 */
export const remapTime = (originalSec: number): number => {
  let t = 0;
  for (const [s, e] of keptSegments) {
    if (originalSec < s) return t;
    if (originalSec < e) return t + (originalSec - s);
    t += e - s;
  }
  return t;
};
