export type SilenceMap = {
  leadingEndSec: number;
  trailingStartSec: number;
  totalDurationSec: number;
  segments: Array<{ startSec: number; endSec: number; durationSec: number }>;
};

// Auto-generated by scripts/parse-silences.mjs — do not edit by hand.
export const silences: SilenceMap = {
  "leadingEndSec": 0,
  "trailingStartSec": 501.005,
  "totalDurationSec": 501.005,
  "segments": []
};
