export type SilenceMap = {
  leadingEndSec: number;
  trailingStartSec: number;
  totalDurationSec: number;
  segments: Array<{ startSec: number; endSec: number; durationSec: number }>;
};

// Auto-generated by scripts/parse-silences.mjs — do not edit by hand.
export const silences: SilenceMap = {
  "leadingEndSec": 0,
  "trailingStartSec": 501.005,
  "totalDurationSec": 501.005,
  "segments": [
    {
      "startSec": 2.217125,
      "endSec": 3.810833,
      "durationSec": 1.593708
    },
    {
      "startSec": 26.381708,
      "endSec": 27.512187,
      "durationSec": 1.130479
    },
    {
      "startSec": 38.388646,
      "endSec": 39.009167,
      "durationSec": 0.620521
    },
    {
      "startSec": 39.438812,
      "endSec": 39.954563,
      "durationSec": 0.51575
    },
    {
      "startSec": 45.674292,
      "endSec": 46.479958,
      "durationSec": 0.805667
    },
    {
      "startSec": 68.618042,
      "endSec": 69.131,
      "durationSec": 0.512958
    },
    {
      "startSec": 90.276167,
      "endSec": 91.104771,
      "durationSec": 0.828604
    },
    {
      "startSec": 91.468896,
      "endSec": 92.450292,
      "durationSec": 0.981396
    },
    {
      "startSec": 97.443854,
      "endSec": 98.284813,
      "durationSec": 0.840958
    },
    {
      "startSec": 98.862708,
      "endSec": 99.490708,
      "durationSec": 0.628
    },
    {
      "startSec": 109.943229,
      "endSec": 110.725958,
      "durationSec": 0.782729
    },
    {
      "startSec": 122.312083,
      "endSec": 122.812417,
      "durationSec": 0.500333
    },
    {
      "startSec": 126.452583,
      "endSec": 127.17575,
      "durationSec": 0.723167
    },
    {
      "startSec": 134.08375,
      "endSec": 134.662875,
      "durationSec": 0.579125
    },
    {
      "startSec": 134.662896,
      "endSec": 135.202917,
      "durationSec": 0.540021
    },
    {
      "startSec": 136.352833,
      "endSec": 137.005104,
      "durationSec": 0.652271
    },
    {
      "startSec": 137.291687,
      "endSec": 138.107583,
      "durationSec": 0.815896
    },
    {
      "startSec": 141.422417,
      "endSec": 142.542146,
      "durationSec": 1.119729
    },
    {
      "startSec": 145.402437,
      "endSec": 146.078292,
      "durationSec": 0.675854
    },
    {
      "startSec": 153.814833,
      "endSec": 154.4965,
      "durationSec": 0.681667
    },
    {
      "startSec": 159.535375,
      "endSec": 160.202687,
      "durationSec": 0.667312
    },
    {
      "startSec": 164.340125,
      "endSec": 165.087583,
      "durationSec": 0.747458
    },
    {
      "startSec": 165.091896,
      "endSec": 166.140958,
      "durationSec": 1.049063
    },
    {
      "startSec": 169.583062,
      "endSec": 170.404812,
      "durationSec": 0.82175
    },
    {
      "startSec": 185.419625,
      "endSec": 186.082375,
      "durationSec": 0.66275
    },
    {
      "startSec": 191.527917,
      "endSec": 192.059104,
      "durationSec": 0.531188
    },
    {
      "startSec": 193.313958,
      "endSec": 193.871083,
      "durationSec": 0.557125
    },
    {
      "startSec": 195.34425,
      "endSec": 196.368604,
      "durationSec": 1.024354
    },
    {
      "startSec": 196.430917,
      "endSec": 197.293813,
      "durationSec": 0.862896
    },
    {
      "startSec": 205.267646,
      "endSec": 205.826625,
      "durationSec": 0.558979
    },
    {
      "startSec": 211.184917,
      "endSec": 211.933083,
      "durationSec": 0.748167
    },
    {
      "startSec": 212.433437,
      "endSec": 212.988583,
      "durationSec": 0.555146
    },
    {
      "startSec": 215.148833,
      "endSec": 216.069562,
      "durationSec": 0.920729
    },
    {
      "startSec": 217.256104,
      "endSec": 218.128938,
      "durationSec": 0.872833
    },
    {
      "startSec": 218.664333,
      "endSec": 220.073375,
      "durationSec": 1.409042
    },
    {
      "startSec": 220.568938,
      "endSec": 221.723479,
      "durationSec": 1.154542
    },
    {
      "startSec": 224.310354,
      "endSec": 224.897625,
      "durationSec": 0.587271
    },
    {
      "startSec": 226.459437,
      "endSec": 227.403042,
      "durationSec": 0.943604
    },
    {
      "startSec": 229.2145,
      "endSec": 229.971667,
      "durationSec": 0.757167
    },
    {
      "startSec": 236.106542,
      "endSec": 236.657729,
      "durationSec": 0.551187
    },
    {
      "startSec": 241.701021,
      "endSec": 242.325958,
      "durationSec": 0.624938
    },
    {
      "startSec": 244.468167,
      "endSec": 245.545063,
      "durationSec": 1.076896
    },
    {
      "startSec": 251.044875,
      "endSec": 251.742604,
      "durationSec": 0.697729
    },
    {
      "startSec": 285.014437,
      "endSec": 285.789125,
      "durationSec": 0.774687
    },
    {
      "startSec": 286.254958,
      "endSec": 287.831521,
      "durationSec": 1.576562
    },
    {
      "startSec": 294.242917,
      "endSec": 295.117271,
      "durationSec": 0.874354
    },
    {
      "startSec": 301.611312,
      "endSec": 302.388937,
      "durationSec": 0.777625
    },
    {
      "startSec": 331.806708,
      "endSec": 333.441354,
      "durationSec": 1.634646
    },
    {
      "startSec": 340.101833,
      "endSec": 340.930708,
      "durationSec": 0.828875
    },
    {
      "startSec": 344.368542,
      "endSec": 345.164604,
      "durationSec": 0.796063
    },
    {
      "startSec": 369.518562,
      "endSec": 370.643708,
      "durationSec": 1.125146
    },
    {
      "startSec": 379.745812,
      "endSec": 380.456562,
      "durationSec": 0.71075
    },
    {
      "startSec": 381.188542,
      "endSec": 381.872875,
      "durationSec": 0.684333
    },
    {
      "startSec": 394.154063,
      "endSec": 394.773833,
      "durationSec": 0.619771
    },
    {
      "startSec": 398.097562,
      "endSec": 398.625812,
      "durationSec": 0.52825
    },
    {
      "startSec": 425.979479,
      "endSec": 426.567875,
      "durationSec": 0.588396
    },
    {
      "startSec": 445.008875,
      "endSec": 445.604667,
      "durationSec": 0.595792
    },
    {
      "startSec": 460.298667,
      "endSec": 460.81575,
      "durationSec": 0.517083
    },
    {
      "startSec": 472.785708,
      "endSec": 473.493437,
      "durationSec": 0.707729
    },
    {
      "startSec": 478.114896,
      "endSec": 478.827063,
      "durationSec": 0.712167
    },
    {
      "startSec": 482.613771,
      "endSec": 483.526708,
      "durationSec": 0.912937
    }
  ]
};
