export type ViralCaption = {
  startSec: number;
  endSec: number;
  jp: string;
  bn: string;
  en: string;
};

// Auto-generated by scripts/build-viral-cut.mjs from public/viral-cut.json.
// Captions are in the NEW concatenated timeline of public/viral-cut.mp4
// (each pick laid end-to-end starting at 0).

export const viralCutDurationSec = 75.232;

export const viralCutCaptions: ViralCaption[] = [
  {
    "startSec": 0,
    "endSec": 15.088,
    "jp": "このコミュニティや社会に、一メンバーとしてどう貢献できるか、続けたいと思っています。そして、建築エンジニアとしての自分の能力も。",
    "bn": "এই সোসাইটিতে কিংবা এই সমাজে কিভাবে আরও একজন সদস্য হিসেবে অবদান ডাকতে পারেন, সেককুমভাবে চলতে চাই, সেই সাথে অবশ্যই নিজের যে আর্কি ইঞ্জিনিয়ার হিসেবে আছে, সেই ক্ষেত্রে নিজের",
    "en": "I want to continue contributing to this community or society as a member, and of course, using my skills as an architectural engineer."
  },
  {
    "startSec": 15.088,
    "endSec": 28.064,
    "jp": "一つ目の理由は、そして二つ目の理由は、日本のライフスタイルです。すべてが規則正しく、清潔な身なりを保ちながらも、すべてが日本に近づくきっかけになっています。",
    "bn": "এটা একটা কারণ এবং দ্বিতিয়টি হচ্ছে জাপানের লাইভস্টাইল, এখানে সবকিছু নিয়ম ক্ষারণমাফিক হয় এবং পরিষ্কার পরেচ্ছন্নেও সবকিছু মিলিয়ে মূলত জাপানী আসার ব্যাপারে সিদ্ধন্তে নেয়া।",
    "en": "This is one reason, and the second is the Japanese lifestyle, where everything is orderly and clean, which ultimately helps me decide to come to Japan."
  },
  {
    "startSec": 28.064,
    "endSec": 45.76,
    "jp": "まず、言いたいのは、この国ではすべてが規則通りに進むこと。私たちの国では、忠誠心が見られるかもしれませんが、日本では、ルールが非常に厳格で、ルールが全てではない、ということです。",
    "bn": "প্রথমোত যেটা বলতে চাই, সবকিছু এখানে নিয়ম মাফিক হয়, তো আমাদের দেশে যেজি নিষ্ঠা দেখা যায় যে এই ক্ষেত্রে হয়তো একটু নিষ্ঠিত হতে পারে, কিন্তু জাপানের সবকিছু নিয়ম মাফিক, যে হয়তো নিয়ম কাননগুলো একটু কঠিন হলেও সবগিলো নিয়ম সবকিছু নি",
    "en": "First of all, I want to say that everything here is orderly. While our country might show loyalty, in Japan, everything is highly regulated, and the rules are not everything."
  },
  {
    "startSec": 45.76,
    "endSec": 58.88,
    "jp": "ビジネス文化や日本の文化について少しは理解していましたが、実際に経験してみると、それは基本的にライフスタイルなのだと感じました。",
    "bn": "বিজিনেস কালচার এবং জাপানের যে কালচার সম্পর্কে কিছুটা ধারণা ছিল, কিন্তু যতটাই ধারণা থাক নিখান আসলে এ সে জীবনযাত্রা যেমনটা হয় আসলে,",
    "en": "I had some idea of business culture and Japanese culture, but as far as I can tell, it is fundamentally a way of life."
  },
  {
    "startSec": 58.88,
    "endSec": 75.232,
    "jp": "職場の文化は、バングラデシュと日本とでは少し違うと思いますので、最初は少し時間をかけて、少しずつ慣れていく必要があると思います。",
    "bn": "বাংলাদেশে আসলে কাজ করার যে কালচার এবং জাপানে সদস্যরই কাজ করার যে কালচার এটা আমি মনে করি কিছুটা আলাদা এজন্য প্রথমে অবস্থতে একটু সময় লাখিতে পারে এই জিনিসটা একটু চিন্থাবনা করে পোস্ততি নিয়ে আশা উজিত করে মনে করে।",
    "en": "I think the work culture in Bangladesh and the work culture in Japan are a little different, so I think it might take some time to get used to it."
  }
];
