export type ViralCaption = {
  startSec: number;
  endSec: number;
  jp: string;
  bn: string;
  en: string;
};

// Auto-generated by scripts/build-viral-cut.mjs from public/viral-cut.json.
// Captions are in the NEW concatenated timeline of public/viral-cut.mp4
// (each pick laid end-to-end starting at 0).

export const viralCutDurationSec = 99.232;

export const viralCutCaptions: ViralCaption[] = [
  {
    "startSec": 0,
    "endSec": 12.976,
    "jp": "その理由は\"つ目 第二の理由は 日本の生活スタイルです 規則を遵守し 清潔な衣装の選択をしても すべてが日本人に 近づくことに繋がっています",
    "bn": "এটা একটা কারণ এবং দ্বিতিয়টি হচ্ছে জাপানের লাইভস্টাইল, এখানে সবকিছু নিয়ম ক্ষারণমাফিক হয় এবং পরিষ্কার পরেচ্ছন্নেও সবকিছু মিলিয়ে মূলত জাপানী আসার ব্যাপারে সিদ্ধন্তে নেয়া।",
    "en": "This is one reason and the second is the Japanese lifestyle, where everything is strictly regulated and everything is taken together in a clean dress, basically to bring the Japanese into the world."
  },
  {
    "startSec": 12.976,
    "endSec": 26.096,
    "jp": "ビジネス文化や日本の文化について ほんの少しの理解がありましたが 概念が深ければ ライフスタイルは",
    "bn": "বিজিনেস কালচার এবং জাপানের যে কালচার সম্পর্কে কিছুটা ধারণা ছিল, কিন্তু যতটাই ধারণা থাক নিখান আসলে এ সে জীবনযাত্রা যেমনটা হয় আসলে,",
    "en": "I had some idea of the business culture and the culture of Japan, but as far as I can tell, it's a way of life as it is."
  },
  {
    "startSec": 26.096,
    "endSec": 43.792,
    "jp": "まず,私は言いたいのは,この国では, ルールがすべてあるということです. ルールが少し厳しいかもしれませんが,日本では,ルールがすべてではありません.",
    "bn": "প্রথমোত যেটা বলতে চাই, সবকিছু এখানে নিয়ম মাফিক হয়, তো আমাদের দেশে যেজি নিষ্ঠা দেখা যায় যে এই ক্ষেত্রে হয়তো একটু নিষ্ঠিত হতে পারে, কিন্তু জাপানের সবকিছু নিয়ম মাফিক, যে হয়তো নিয়ম কাননগুলো একটু কঠিন হলেও সবগিলো নিয়ম সবকিছু নি",
    "en": "First of all, I want to say that everything is by the rules, and the loyalty that we have in this country is that it may be a little bit of a loyalty, but in Japan everything is by the rules, and the rules are a little bit hard, but the rules are not everything."
  },
  {
    "startSec": 43.792,
    "endSec": 48.72,
    "jp": "適切なタイミングで守られれば この日曜日がとてもポジティブに思えました",
    "bn": "মেনে এবং সঠিক সময়ে পালন করা হয়ে, এই দিনিসটি আমার কাছে বেশ পজিটিভ মনে হয়েছে।",
    "en": "By being observed and observed in the right time, this day has been very positive to me."
  },
  {
    "startSec": 48.72,
    "endSec": 63.808,
    "jp": "コミュニティやコミュニティの他のメンバーとして 貢献したいのです 建築技術者としての自分の能力も",
    "bn": "এই সোসাইটিতে কিংবা এই সমাজে কিভাবে আরও একজন সদস্য হিসেবে অবদান ডাকতে পারেন, সেককুমভাবে চলতে চাই, সেই সাথে অবশ্যই নিজের যে আর্কি ইঞ্জিনিয়ার হিসেবে আছে, সেই ক্ষেত্রে নিজের",
    "en": "I want to continue to do this as a way to contribute to this society, as a member of this society, and as an archiving engineer, of course, to my own interests."
  },
  {
    "startSec": 63.808,
    "endSec": 77.04,
    "jp": "コミュニケーション能力の向上も 重要だということです だから私は個人的に できるだけ日本語を 聴いて 実践することに 取り組んでいます",
    "bn": "জেইল-পিটির সার্টিফিকেট থাকা এবং কমিউনিকেশনের অ্যাবিলিটি তৈরি করাতেও টালাদে ব্যাপার, এজন্য আমি ব্যক্তিকভাবে সাজিসন দ্বিপুর হচ্ছে, যথা সম্ভব, জাপানিজ শুনে শুনে প্যাক্টিস করা, অর্থা বিভিন্ন মানুষের",
    "en": "It's also a matter of getting a jail-PTI certificate and building communication skills, so I personally am passionate about, as much as possible, listening to Japanese, which means different people."
  },
  {
    "startSec": 77.04,
    "endSec": 99.232,
    "jp": "この国の法律は,バングラデシュの法律とは全く違います.この場合,私は皆さんにお願いします,日本法です.",
    "bn": "এই দেশের নিয়মকানুন, বাংলাদেশের নিয়মকানুন থেকে অনেকটাই আলাদা।এক্ষেত্রে, আমার অনুরোধ থাকবে, সবাই অবশ্যই জাপানের নিয়মকানুন, সেটি কি আছে পরিচিত যংহ কিংবা আপনার যথেকে কোনো জিনসির মাধ্যমে আসেন তাদের কাছ থেকে যে নেই, সে এই নিয়মকা�",
    "en": "The rules of this country are very different from the rules of Bangladesh. In this case, I would ask everyone to follow the rules of Japan, whether it is known to you or from any of the species you come from."
  }
];
