export type ViralCaption = {
  startSec: number;
  endSec: number;
  jp: string;
  bn: string;
  en: string;
};

// Auto-generated by scripts/build-viral-cut.mjs from public/viral-cut.json.
// Captions are in the NEW concatenated timeline of public/viral-cut.mp4
// (each pick laid end-to-end starting at 0).
//
// Until the pipeline runs, this is a placeholder so the composition compiles.

export const viralCutDurationSec = 60;

export const viralCutCaptions: ViralCaption[] = [];
